project:
  type: website

website:
  title: "Nam Vien"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: Portfolio.qmd
        text: Portfolio
      - href: About.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: coursework.qmd
        text: Coursework  

  page-footer:
    right: "&copy; 2025 Nam Vien"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto
  

